### ISSUE TITLE
何の言語・ライブラリで書きますか

### ISSUE THREAD

**Issue by wass80** [kmc-jp/ult-twiclient#10]

**Comment by utgwkk** [comment]
Electronで良いのでは。  
HTML&JavaScriptなのでとっつきやすそう(ほんまか)。

**Comment by utgwkk** [comment]
- [Electronでアプリケーションを作ってみよう](http://qiita.com/Quramy/items/a4be32769366cfe55778)

**Comment by wass80** [comment]
+1

**Comment by utgwkk** [comment]
CSSもあった。

**Comment by pastak** [comment]
ElectronでTwitterクライアント書く情報です
- http://r7kamura.hatenablog.com/entry/2015/08/25/154846
- https://electron-jp-slackin.herokuapp.com/

**Comment by utgwkk** [comment]
めっちゃ作られてる。。

**Comment by wass80** [comment]
ElectronとBabelは確定として, React的なものを使うか否か

**Comment by MSZ006AEUG** [comment]
What is Babel?

**Comment by wass80** [comment]
Javascriptの新しいバージョン(ES6)でコーディングできるようになるライブラリです
https://babeljs.io/

**Comment by wass80** [comment]
Javascriptの新しいバージョン(ES6+)で書くためのライブラリです

**Comment by monad-san** [comment]
React使うならReduxとかどうでしょうか。
https://github.com/rackt/redux
最近ではcycle.jsってのもあるみたいです。
http://cycle.js.org/

BabelはES6のコードをES5に(だいたい)変換するブツです。

**Comment by utgwkk** [comment]
vue.js 使おう
http://jp.vuejs.org/

**Comment by wass80** [comment]
使う。
