### ISSUE TITLE
access tokenを保存してほしい

### ISSUE THREAD

**Issue by wass80** [kmc-jp/ult-twiclient#15]
保存されているならば, apiを得られる,
保存されていなければ, 認証画面に飛ぶ
↑をうまく実装できるような形で関数を提供してほしい

**Comment by wass80** [comment]
settingの保存として別のファイルに切ったほうが良さそう

common/setting.js を書いて,
その関数をcommon/oauth.js で呼びましょう

**Comment by pastak** [comment]
indexedDBとかを使えば良さそう

**Comment by wass80** [comment]
それも保存されるんですね!
最高ですね!

**Comment by wass80** [comment]
その実装でさくっと書いてみます
