### ISSUE TITLE
認証のpinコードを自動取得する

### ISSUE THREAD

**Issue by wass80** [kmc-jp/ult-twiclient#22]
フローをもう少し楽にしたい

webviewの中を見れないなら、
認証の流れをわかりやすくしたい

**Comment by pastak** [comment]
過去にOAuth実装した時は
- BrowserWindowを作る
- OAuthの認証URLを開く
- [`webContents.on('did-get-redirect-request')`](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#event-did-get-redirect-request)で`newUrl`を取得する
- 認証された`newUrl`が指定したcallbackURLとマッチしたら、`?code=`以降に認証codeが入ってるのでそれを使って、tokenを取得して保存する
- BrowserWindowを閉じる

という感じにしました

**Comment by wass80** [comment]
なるほど！その方法良いですね。
書き換えます
