### ISSUE TITLE
ツイートボタン以外にCtrl+Enterでツイート送信したい。

### ISSUE THREAD

**Issue by MSZ006AEUG** [kmc-jp/ult-twiclient#35]
ソースのツイート送信部分isどこ？

**Comment by wass80** [comment]
https://github.com/kmc-jp/ult-twiclient/blob/master/app/index.js#L48-L59

**Comment by MSZ006AEUG** [comment]
これキーボード入力になると書き方変わるよね？

**Comment by wass80** [comment]
input の keydown イベントで Ctrl+Enter を認識すれば良さそう
